### ISSUE TITLE
documentation enhancement proposal

### ISSUE THREAD

**Issue by demarey** [ba-st/Bell#5]
Hi,

It would be nice to have a few examples of logging, including structured data to have a better feeling of what this lib can help for.

**Comment by gcotelli** [comment]
Nice idea. I will try to pull up some examples so it's easier to grasp the scope. We're planning to consolidate here all the observability-related bits that now are scattered in different projects.

**Comment by demarey** [comment]
Thanks. It helps a lot to get fast feeling on how this lib cane help.
